version: '3'

services:
  web:
    build: web
    volumes:
      - ../app/:/var/www/html/
    working_dir: /var/www/html
    ports:
      - "80:80"

  db:
    build: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - ./db/base:/db
    working_dir: /db

